//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angularvizeproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevaplartbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cevaplartbl()
        {
            this.sorulartbl1 = new HashSet<sorulartbl>();
        }
    
        public int cevapid { get; set; }
        public Nullable<int> soruid { get; set; }
        public Nullable<int> uyeid { get; set; }
        public string cevap { get; set; }
        public string tarih { get; set; }
    
        public virtual sorulartbl sorulartbl { get; set; }
        public virtual uyelertbl uyelertbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sorulartbl> sorulartbl1 { get; set; }
    }
}
