//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angularvizeproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorulartbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sorulartbl()
        {
            this.cevaplartbl = new HashSet<cevaplartbl>();
        }
    
        public int soruid { get; set; }
        public string soru { get; set; }
        public Nullable<int> kategoriid { get; set; }
        public string tarih { get; set; }
        public Nullable<int> uyeid { get; set; }
        public Nullable<int> cevapid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cevaplartbl> cevaplartbl { get; set; }
        public virtual cevaplartbl cevaplartbl1 { get; set; }
        public virtual kategoritbl kategoritbl { get; set; }
        public virtual uyelertbl uyelertbl { get; set; }
    }
}
